version: '3.8'

services:
  visri_db:
    image: postgis/postgis:15-3.3
    container_name: visri_postgis
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=visri_spatial
    ports:
      - "5432:5432"
    volumes:
      - visri_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  visri_db_data:
